name: Build and Deploy Container

on:
  workflow_dispatch:

env:
  IMAGE_REPOSITORY: kalukwo/nivela-backend

jobs:
  build:
    name: Build and Push .NET API Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout API Source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Runtime Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: runtime
          push: true
          tags: ${{ env.IMAGE_REPOSITORY }}:latest

      - name: Build and Push Migration Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: migrations
          push: true
          tags: ${{ env.IMAGE_REPOSITORY }}:migrations

  trigger-remote:
    name: Trigger Remote Deployment
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Trigger remote workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GCP_TRIGGER_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Kalukwo/NivelaInfrastructure/actions/workflows/deploy_gcp.yml/dispatches \
            -d '{"ref":"main"}'